# Generated by Django 5.0 on 2024-04-10 22:02

import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctorado',
            fields=[
                ('idDoctorado', models.AutoField(primary_key=True, serialize=False)),
                ('des_doctorado', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('idEvaluacion', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_evaluacion', models.CharField(max_length=10, null=True, unique=True)),
                ('estado_evaluacion', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='Maestria',
            fields=[
                ('idMaestria', models.AutoField(primary_key=True, serialize=False)),
                ('des_maestria', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Modalidad',
            fields=[
                ('idModalidad', models.AutoField(primary_key=True, serialize=False)),
                ('des_modalidad', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('idUnidad', models.AutoField(primary_key=True, serialize=False)),
                ('des_unidad', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleEvaluacion',
            fields=[
                ('idDetalleEva', models.AutoField(primary_key=True, serialize=False)),
                ('puntaje_promedioP', models.DecimalField(decimal_places=2, default=6.0, max_digits=5, validators=[django.core.validators.MinValueValidator(6.0), django.core.validators.MaxValueValidator(12.0)])),
                ('puntaje_cursosEva', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(4.0)])),
                ('puntaje_partCientifica', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(4.0)])),
                ('puntaje_docenciaUni', models.DecimalField(decimal_places=2, default=0.5, max_digits=5, validators=[django.core.validators.MinValueValidator(0.5), django.core.validators.MaxValueValidator(3.0)])),
                ('puntaje_idiomaExt', models.DecimalField(decimal_places=2, default=0.5, max_digits=5, validators=[django.core.validators.MinValueValidator(0.5), django.core.validators.MaxValueValidator(1.0)])),
                ('puntaje_capacitacion', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MaxValueValidator(24.0)])),
                ('puntaje_libroInscritos', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(2.0)])),
                ('puntaje_publicaciones', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(3.0)])),
                ('puntaje_proyInvestig', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('puntaje_asesoriaProy', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('puntaje_produccionCien', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MaxValueValidator(11.0)])),
                ('puntajeFinal', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MaxValueValidator(35.0)])),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appevaluacion.evaluacion', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Evaluador',
            fields=[
                ('idEvaluador', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_evaluador', models.CharField(default='123456', max_length=6)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=8, null=True)),
                ('email', models.EmailField(max_length=100, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('cargo', models.CharField(choices=[('Presidente', 'Presidente'), ('Secretario', 'Secretario'), ('Vocal', 'Vocal')], default='Presidente', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('unidad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appevaluacion.unidad')),
            ],
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='evaluador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appevaluacion.evaluador'),
        ),
        migrations.CreateModel(
            name='Postulante',
            fields=[
                ('idPostulante', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=10, null=True)),
                ('ap_paterno', models.CharField(max_length=100)),
                ('ap_materno', models.CharField(max_length=100)),
                ('nombres', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('celular', models.CharField(blank=True, max_length=20, null=True)),
                ('pdf_curriculum', models.CharField(blank=True, max_length=200, null=True)),
                ('doctorado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='postulantes_doctorado', to='appevaluacion.doctorado')),
                ('maestria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='postulantes_maestria', to='appevaluacion.maestria')),
                ('modalidad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appevaluacion.modalidad')),
                ('unidad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appevaluacion.unidad')),
            ],
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='postulante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appevaluacion.postulante', unique=True),
        ),
    ]
