# Generated by Django 5.0 on 2024-04-11 18:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appevaluacion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleevaluacion',
            name='puntaje_asesoriaProy',
        ),
        migrations.RemoveField(
            model_name='detalleevaluacion',
            name='puntaje_proyInvestig',
        ),
        migrations.AlterField(
            model_name='detalleevaluacion',
            name='puntajeFinal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MaxValueValidator(40.0)]),
        ),
        migrations.AlterField(
            model_name='detalleevaluacion',
            name='puntaje_capacitacion',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MaxValueValidator(32.0)]),
        ),
        migrations.AlterField(
            model_name='detalleevaluacion',
            name='puntaje_cursosEva',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(3.5)]),
        ),
        migrations.AlterField(
            model_name='detalleevaluacion',
            name='puntaje_docenciaUni',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(14.0)]),
        ),
        migrations.AlterField(
            model_name='detalleevaluacion',
            name='puntaje_idiomaExt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(6.0)]),
        ),
        migrations.AlterField(
            model_name='detalleevaluacion',
            name='puntaje_libroInscritos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.5)]),
        ),
        migrations.AlterField(
            model_name='detalleevaluacion',
            name='puntaje_partCientifica',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AlterField(
            model_name='detalleevaluacion',
            name='puntaje_produccionCien',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MaxValueValidator(8.0)]),
        ),
        migrations.AlterField(
            model_name='detalleevaluacion',
            name='puntaje_promedioP',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(7.5)]),
        ),
        migrations.AlterField(
            model_name='detalleevaluacion',
            name='puntaje_publicaciones',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(6.5)]),
        ),
    ]
