# Generated by Django 5.0 on 2024-04-11 20:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appevaluacion', '0002_remove_detalleevaluacion_puntaje_asesoriaproy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleevaluacion',
            name='puntajeFinal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MaxValueValidator(66.9)]),
        ),
        migrations.AlterField(
            model_name='detalleevaluacion',
            name='puntaje_capacitacion',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MaxValueValidator(47.0)]),
        ),
        migrations.AlterField(
            model_name='detalleevaluacion',
            name='puntaje_cursosEva',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(2.5), django.core.validators.MaxValueValidator(9.5)]),
        ),
        migrations.AlterField(
            model_name='detalleevaluacion',
            name='puntaje_libroInscritos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(8.4)]),
        ),
        migrations.AlterField(
            model_name='detalleevaluacion',
            name='puntaje_partCientifica',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)]),
        ),
        migrations.AlterField(
            model_name='detalleevaluacion',
            name='puntaje_produccionCien',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MaxValueValidator(19.9)]),
        ),
        migrations.AlterField(
            model_name='detalleevaluacion',
            name='puntaje_publicaciones',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(11.5)]),
        ),
    ]
